title: SignalsAPI docs
description: SignalsAPI documentation
theme: just-the-docs

color_scheme: signalsapi

url: https://docs.signalsapi.com/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
