# frozen_string_literal: true

# Story 7.10: the phone page's mobile-support claim is generated by looping
# over site.data.providers.items filtered on mobile_support, so no line of
# its body should hand-type a provider name outside a Liquid tag.
MOBILE_CLAIM_PAGE = "features/find-phone-numbers.md"

Check.register(
  id: "mobile-claim-generated",
  desc: "The phone page names mobile-support providers via Liquid, not hand-written prose",
  covers: ["7.10"]
) do |site|
  site.fail!("_data/providers.yml is missing") unless site.data["providers"]

  page = site.pages.find { |p| p.path == MOBILE_CLAIM_PAGE }
  site.fail!("#{MOBILE_CLAIM_PAGE} is missing") unless page

  provider_names = site.data["providers"]["items"].map { |p| p["name"] }
  offenders = []

  page.body.each_line do |line|
    # Strip Liquid tags before checking — a line can legitimately carry a
    # tag (e.g. an include) alongside a hand-typed name outside it.
    outside_liquid = line.gsub(/\{%.*?%\}/, "").gsub(/\{\{.*?\}\}/, "")
    provider_names.each { |name| offenders << name if outside_liquid.include?(name) }
  end

  unless offenders.empty?
    site.fail!("provider name(s) hand-written into prose instead of rendered from data — #{offenders.uniq.join(', ')}")
  end
end
